server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///home/zhenglai/repo/hello-ms/confsvr/src/main/resources/config/licensingservice

